spring.application.name: kk-eventos

spring.rabbitmq:
  host: k8s-lia.unrn.edu.ar
  port: 30567
  username: taller
  password: taller.2024

spring.cloud.stream.defaultBinder: rabbit

spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: keycloaktaller
    group: videoclub00

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
  bindingRoutingKey: "KK.EVENT.*.videoclub00.#"
  autoBindDlq: true
  republishToDlq: true
  deadLetterExchange: keycloaktaller
  deadLetterQueueName: videoclub00.dlq