spring.application.name: kk-eventos

spring.rabbitmq:
  host: localhost #k8s-lia.unrn.edu.ar
  port: 30567
  username: taller
  password: taller.2024

spring.cloud.stream.defaultBinder: rabbit

spring.cloud.function.definition: eventMovieProcessor;eventActorProcessor;keycloakProcessor

spring.cloud.stream:
  default.contentType: application/json
  bindings:
    eventMovieProcessor-in-0:
      destination: eventMovie
      group: eventGroup
    eventMovieProcessor-out-0:
      destination: eventMovie
      producer:
        required-groups: auditGroup
    eventActorProcessor-in-0:
      destination: eventActor
      group: eventGroup
    eventActorProcessor-out-0:
      destination: eventActor
      producer:
        required-groups: auditGroup

spring.cloud.stream.bindings.eventMovieProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.eventMovieProcessor-in-0.consumer:
  #bindingRoutingKey: Movie.#
  autoBindDlq: true
  republishToDlq: true
  deadLetterExchange: eventMovieDLX
  deadLetterQueueName: eventMovie.eventGroup.dlq

spring.cloud.stream.bindings.eventActorProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.eventActorProcessor-in-0.consumer:
  #bindingRoutingKey: Actor.#
  autoBindDlq: true
  republishToDlq: true
  deadLetterExchange: eventActorDLX
  deadLetterQueueName: eventActor.eventGroup.dlq

# keycloak exchange keycloaktaller para todos
spring.cloud.stream.bindings.keycloakProcessor-in-0:
  destination: keycloaktaller
  group: videoclub00

spring.cloud.stream.bindings.keycloakProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.keycloakProcessor-in-0.consumer:
  bindingRoutingKey: "KK.EVENT.*.videoclub00.#"
  autoBindDlq: true
  republishToDlq: true
  deadLetterExchange: keycloaktaller-videoclub00-DLQ
  deadLetterQueueName: keycloaktaller.videoclub00.dlq